# Close-SourceIssues.ps1
# Generated by migrate-issues.ps1
# Run this to add a migration link comment and close all open source issues

$sourceRepo = "FsLightning/LightningCAD"
$map = Import-Csv "D:\MakeX\Envelop\Lightning\LightningCADTracker\_migration_map.csv"
$closedCount = 0

foreach ($row in $map) {
    $oldNum = $row.SourceNumber
    $newNum = $row.TargetNumber
    $comment = "This issue has been migrated to FsLightning/LightningCADTracker#. Please continue discussion there."

    Write-Host "[#] Adding comment and closing..."
    gh issue comment $oldNum -R $sourceRepo --body "$comment" 2>&1 | Out-Null
    if ($row.State -eq "OPEN") {
        gh issue close $oldNum -R $sourceRepo --comment "Migrated to FsLightning/LightningCADTracker" 2>&1 | Out-Null
    }
    $closedCount++
    Start-Sleep -Milliseconds 200
}
Write-Host "Done! Processed $closedCount source issues." -ForegroundColor Green
